import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import catalogRoutes from './routes/catalogRoutes.js';
import orderRoutes from './routes/orderRoutes.js';
import ticketRoutes from './routes/ticketRoutes.js';
import vendorRoutes from './routes/vendorRoutes.js';
import riderRoutes from './routes/riderRoutes.js';
import supportRoutes from './routes/supportRoutes.js';
import mapRoutes from './routes/mapRoutes.js';
import adminRoutes from './routes/adminRoutes.js';

const app = express();
const port = Number(process.env.PORT || 4005);
const origins = (process.env.CORS_ORIGINS || 'http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177').split(',');
app.use(helmet());
app.use(cors({ origin: (origin, cb) => cb(null, !origin || origins.includes(origin)), credentials: true }));
app.use(morgan('dev'));
app.use(express.json({ limit: '2mb' }));
app.get('/healthz', (_req, res) => res.json({ ok: true, app: 'sokoeats' }));
app.use('/api', catalogRoutes);
app.use('/api', orderRoutes);
app.use('/api', ticketRoutes);
app.use('/api', vendorRoutes);
app.use('/api', riderRoutes);
app.use('/api', supportRoutes);
app.use('/api', mapRoutes);
app.use('/api/admin', adminRoutes);
app.use((req, res) => res.status(404).json({ message: `No Sokoeats route for ${req.method} ${req.path}` }));
app.use((err, _req, res, _next) => {
  console.error(err);
  res.status(err.status || 500).json({ message: err.message || 'Internal Server Error' });
});
app.listen(port, '0.0.0.0', () => console.log(`Sokoeats API listening on :${port}`));
