import { Router } from 'express';
import { createOrder, listOrders, updateOrderStatus } from '../controllers/orderController.js';
import { validate } from '../validators/validate.js';
import { createOrderSchema, updateOrderStatusSchema } from '../validators/orderValidator.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { quoteOrder } from '../controllers/pricingController.js';
import { pricingQuoteSchema } from '../validators/pricingValidator.js';
import { deliveryOrders, trackDelivery, deliveryAction, shareDeliveryLocation } from '../controllers/deliveryController.js';
import { deliveryActionSchema, deliveryLocationSchema } from '../validators/deliveryValidator.js';
const router = Router();
router.get('/deliveries', requireAuth, deliveryOrders);
router.get('/deliveries/:orderKey', requireAuth, trackDelivery);
router.post('/deliveries/:orderKey/actions', requireAuth, validate(deliveryActionSchema), deliveryAction);
router.post('/deliveries/:orderKey/location', requireAuth, validate(deliveryLocationSchema), shareDeliveryLocation);
router.get('/orders', requireAuth, requireRole('admin', 'support'), listOrders);
router.post('/orders/quote', requireAuth, requireRole('customer'), validate(pricingQuoteSchema), quoteOrder);
router.post('/orders', requireAuth, validate(createOrderSchema), createOrder);
router.patch('/orders/:id/status', requireAuth, requireRole('admin', 'support'), validate(updateOrderStatusSchema), updateOrderStatus);
export default router;
