import { Router } from 'express';
import { createOrder, listOrders, updateOrderStatus } from '../controllers/orderController.js';
import { validate } from '../validators/validate.js';
import { createOrderSchema, updateOrderStatusSchema } from '../validators/orderValidator.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
const router = Router();
router.get('/orders', requireAuth, requireRole('admin', 'support'), listOrders);
router.post('/orders', requireAuth, validate(createOrderSchema), createOrder);
router.patch('/orders/:id/status', requireAuth, requireRole('admin', 'support'), validate(updateOrderStatusSchema), updateOrderStatus);
export default router;
