import { Router } from 'express';
import { acceptDeliveryRequest, activeDelivery, confirmPickup, confirmScanPayment, confirmScanPaymentStatus, incidentConfirmation, liveChatSupport, markArrived, quizResultsFeedback, referralRewards, requestRiderPayout, resolvedTicketDetails, riderEarnings, riderHelpCenter, riderHome, riderLeaderboard, riderOnboarding, riderOrderDetails, riderPayoutConfirmation, riderProfileRatings, riderReferralSuite, riderSupportTrainingSuite, riderTrainingDashboard, riderTrainingLesson, riderTrainingQuiz, safetyIncidentReport, sendReferralInvitations, sendRiderChatMessage, submitSafetyIncident, submitTrainingQuiz, supportTicketHistory, topUpWallet, transactionHistory, updateRiderOnboardingStep, walletPaymentSuite, withdrawWallet } from '../controllers/riderController.js';
import { validate } from '../validators/validate.js';
import { incidentReportSchema, quizSubmissionSchema, referralInvitationsSchema, riderChatMessageSchema, riderOnboardingStepSchema, scanPaymentSchema, walletTopUpSchema, walletWithdrawSchema } from '../validators/interactionValidator.js';

const router = Router();
router.get('/rider/home', riderHome);
router.get('/wallet/payment-suite', walletPaymentSuite);
router.post('/wallet/top-ups', validate(walletTopUpSchema), topUpWallet);
router.post('/wallet/withdrawals', validate(walletWithdrawSchema), withdrawWallet);
router.post('/wallet/scan-payments', validate(scanPaymentSchema), confirmScanPayment);
router.post('/wallet/scan-payments/:reference/confirm', confirmScanPaymentStatus);
router.get('/wallet/transactions', transactionHistory);
router.get('/rider/referrals-suite', riderReferralSuite);
router.post('/rider/referrals/invitations', validate(referralInvitationsSchema), sendReferralInvitations);
router.get('/rider/referrals/rewards', referralRewards);
router.get('/rider/incidents/confirmation', incidentConfirmation);
router.get('/rider/support/tickets', supportTicketHistory);
router.get('/rider/support/tickets/INC-82941', resolvedTicketDetails);
router.get('/rider/support-training-suite', riderSupportTrainingSuite);
router.get('/rider/help-center', riderHelpCenter);
router.get('/rider/live-chat', liveChatSupport);
router.post('/rider/live-chat/messages', validate(riderChatMessageSchema), sendRiderChatMessage);
router.get('/rider/incidents/report', safetyIncidentReport);
router.post('/rider/incidents', validate(incidentReportSchema), submitSafetyIncident);
router.get('/rider/orders/SKO-1294', riderOrderDetails);
router.get('/rider/training', riderTrainingDashboard);
router.get('/rider/training/customer-service', riderTrainingLesson);
router.get('/rider/training/quiz', riderTrainingQuiz);
router.post('/rider/training/quiz/submissions', validate(quizSubmissionSchema), submitTrainingQuiz);
router.get('/rider/training/quiz/results', quizResultsFeedback);
router.get('/rider/onboarding', riderOnboarding);
router.patch('/rider/onboarding/:screenKey', validate(riderOnboardingStepSchema), updateRiderOnboardingStep);
router.get('/rider/earnings', riderEarnings);
router.post('/rider/payouts', requestRiderPayout);
router.get('/rider/payout-confirmation', riderPayoutConfirmation);
router.get('/rider/leaderboard', riderLeaderboard);
router.get('/rider/profile-ratings', riderProfileRatings);
router.get('/rider/active-delivery', activeDelivery);
router.post('/rider/requests/:id/accept', acceptDeliveryRequest);
router.post('/rider/deliveries/:orderCode/arrived', markArrived);
router.post('/rider/deliveries/:orderCode/pickup', confirmPickup);

export default router;
