import { Router } from 'express';
import { createVendor, vendorDashboard } from '../controllers/vendorController.js';
import { campaignHistory, campaignPerformance, createCampaign, createMerchantMenuCategory, createMerchantMenuItem, createVendorImageUpload, importMerchantMenu, launchMerchantAd, marketingAssetsLibrary, merchantGrowthSuite, merchantOperationsSuite, monthlyStatementDetail, requestMerchantPayout, reviewVendor, taxBillingStatements, updateInventoryStock, updateMenuAvailability, updateOwnedVendorOrder, updateVendorOrderStatus, updateVendorProfileSettings, updateVendorStoreProfile, vendorAnalytics, vendorFinanceSuite, vendorInventory, vendorMenu, vendorOperations, vendorOrderDetails, vendorOrderHistory, vendorPortal, vendorProfileSettings } from '../controllers/vendorExperienceController.js';
import { validate } from '../validators/validate.js';
import { vendorSchema } from '../validators/vendorValidator.js';
import { campaignCreateSchema, inventoryStockSchema, menuAvailabilitySchema, merchantAdLaunchSchema, merchantBulkImportSchema, merchantMenuCategorySchema, merchantMenuItemSchema, merchantOnboardingSubmissionSchema, merchantPayoutRequestSchema, vendorOrderStatusSchema, vendorImageUploadSchema, vendorProfileSettingsSchema, vendorReviewSchema } from '../validators/interactionValidator.js';
import { requireAuth, requireRole, requireVerifiedVendor } from '../middleware/auth.js';
import { updateMerchantMenuItem, deleteMerchantMenuItem } from '../controllers/vendorExperienceController.js';
import { merchantMenuItemUpdateSchema } from '../validators/interactionValidator.js';
import { updateProfile } from '../controllers/authController.js';
import { updateProfileSchema } from '../validators/authValidator.js';
const router = Router();
router.get('/vendor-dashboard', vendorDashboard);
router.post('/vendor/onboarding/submissions', (_req, res) => res.status(410).json({ message: 'Create a verified partner application through /api/auth/register with explicit terms acceptance.' }));
router.post('/vendor/onboarding/terms', validate(updateProfileSchema), updateProfile);
router.use('/vendor', requireAuth, requireRole('vendor', 'merchant'));
router.get('/vendor/portal', vendorPortal);
router.get('/vendor/merchant-operations-suite', merchantOperationsSuite);
router.post('/vendor/menu/categories', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, validate(merchantMenuCategorySchema), createMerchantMenuCategory);
router.post('/vendor/media/presign', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, validate(vendorImageUploadSchema), createVendorImageUpload);
router.post('/vendor/menu/items', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, validate(merchantMenuItemSchema), createMerchantMenuItem);
router.put('/vendor/menu/items/:id', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, validate(merchantMenuItemUpdateSchema), updateMerchantMenuItem);
router.delete('/vendor/menu/items/:id', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, deleteMerchantMenuItem);
router.post('/vendor/menu/imports', validate(merchantBulkImportSchema), importMerchantMenu);
router.post('/vendor/ads/launches', validate(merchantAdLaunchSchema), launchMerchantAd);
router.get('/vendor/growth-suite', merchantGrowthSuite);
router.get('/vendor/finance-suite', vendorFinanceSuite);
router.post('/vendor/payouts', validate(merchantPayoutRequestSchema), requestMerchantPayout);
router.get('/vendor/billing/statements', taxBillingStatements);
router.get('/vendor/billing/statements/monthly', monthlyStatementDetail);
router.get('/vendor/marketing/assets', marketingAssetsLibrary);
router.post('/vendor/campaigns', validate(campaignCreateSchema), createCampaign);
router.get('/vendor/campaigns/performance', campaignPerformance);
router.get('/vendor/campaigns/history', campaignHistory);
router.get('/vendor/orders/history', vendorOrderHistory);
router.get('/vendor/orders/SKO-1294/details', vendorOrderDetails);
router.get('/vendor/profile-settings', vendorProfileSettings);
router.patch('/vendor/profile-settings', validate(vendorProfileSettingsSchema), updateVendorProfileSettings);
router.get('/vendor/menu', requireAuth, requireRole('vendor', 'merchant'), vendorMenu);
router.get('/vendor/operations', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, vendorOperations);
router.patch('/vendor/store-profile', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, validate(vendorProfileSettingsSchema), updateVendorStoreProfile);
router.patch('/vendor/orders/:orderKey/workflow', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, validate(vendorOrderStatusSchema), updateOwnedVendorOrder);
router.post('/vendors/:vendorId/reviews', requireAuth, requireRole('customer'), validate(vendorReviewSchema), reviewVendor);
router.get('/vendor/analytics', vendorAnalytics);
router.get('/vendor/inventory', vendorInventory);
router.patch('/vendor/inventory/:id', validate(inventoryStockSchema), updateInventoryStock);
router.patch('/vendor/menu/:id/availability', requireAuth, requireRole('vendor', 'merchant'), requireVerifiedVendor, validate(menuAvailabilitySchema), updateMenuAvailability);
router.patch('/vendor/orders/:code/status', validate(vendorOrderStatusSchema), updateVendorOrderStatus);
router.post('/vendors', requireAuth, requireRole('admin', 'vendor', 'merchant'), validate(vendorSchema), createVendor);
export default router;
