import { Router } from 'express';
import { createVendor, vendorDashboard } from '../controllers/vendorController.js';
import { acceptMerchantTerms, campaignHistory, campaignPerformance, createCampaign, createMerchantMenuItem, importMerchantMenu, launchMerchantAd, marketingAssetsLibrary, merchantGrowthSuite, merchantOperationsSuite, monthlyStatementDetail, requestMerchantPayout, submitMerchantOnboarding, taxBillingStatements, updateInventoryStock, updateMenuAvailability, updateVendorOrderStatus, updateVendorProfileSettings, vendorAnalytics, vendorFinanceSuite, vendorInventory, vendorMenu, vendorOrderDetails, vendorOrderHistory, vendorPortal, vendorProfileSettings } from '../controllers/vendorExperienceController.js';
import { validate } from '../validators/validate.js';
import { vendorSchema } from '../validators/vendorValidator.js';
import { campaignCreateSchema, inventoryStockSchema, menuAvailabilitySchema, merchantAdLaunchSchema, merchantBulkImportSchema, merchantMenuItemSchema, merchantOnboardingSubmissionSchema, merchantPayoutRequestSchema, vendorOrderStatusSchema, vendorProfileSettingsSchema } from '../validators/interactionValidator.js';
const router = Router();
router.get('/vendor-dashboard', vendorDashboard);
router.get('/vendor/portal', vendorPortal);
router.get('/vendor/merchant-operations-suite', merchantOperationsSuite);
router.post('/vendor/onboarding/submissions', validate(merchantOnboardingSubmissionSchema), submitMerchantOnboarding);
router.post('/vendor/onboarding/terms', validate(merchantOnboardingSubmissionSchema), acceptMerchantTerms);
router.post('/vendor/menu/items', validate(merchantMenuItemSchema), createMerchantMenuItem);
router.post('/vendor/menu/imports', validate(merchantBulkImportSchema), importMerchantMenu);
router.post('/vendor/ads/launches', validate(merchantAdLaunchSchema), launchMerchantAd);
router.get('/vendor/growth-suite', merchantGrowthSuite);
router.get('/vendor/finance-suite', vendorFinanceSuite);
router.post('/vendor/payouts', validate(merchantPayoutRequestSchema), requestMerchantPayout);
router.get('/vendor/billing/statements', taxBillingStatements);
router.get('/vendor/billing/statements/monthly', monthlyStatementDetail);
router.get('/vendor/marketing/assets', marketingAssetsLibrary);
router.post('/vendor/campaigns', validate(campaignCreateSchema), createCampaign);
router.get('/vendor/campaigns/performance', campaignPerformance);
router.get('/vendor/campaigns/history', campaignHistory);
router.get('/vendor/orders/history', vendorOrderHistory);
router.get('/vendor/orders/SKO-1294/details', vendorOrderDetails);
router.get('/vendor/profile-settings', vendorProfileSettings);
router.patch('/vendor/profile-settings', validate(vendorProfileSettingsSchema), updateVendorProfileSettings);
router.get('/vendor/menu', vendorMenu);
router.get('/vendor/analytics', vendorAnalytics);
router.get('/vendor/inventory', vendorInventory);
router.patch('/vendor/inventory/:id', validate(inventoryStockSchema), updateInventoryStock);
router.patch('/vendor/menu/:id/availability', validate(menuAvailabilitySchema), updateMenuAvailability);
router.patch('/vendor/orders/:code/status', validate(vendorOrderStatusSchema), updateVendorOrderStatus);
router.post('/vendors', validate(vendorSchema), createVendor);
export default router;
